//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "gallery")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub pk: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub discord_channel_id: i64,
    pub date_created: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::gallery_post::Entity")]
    GalleryPost,
}

impl Related<super::gallery_post::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GalleryPost.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
