//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "gallery_post")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub pk: Uuid,
    pub gallery: Uuid,
    pub discord_message_id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub source_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub media_url: Option<String>,
    pub media_width: Option<i32>,
    pub media_height: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub thumbnail_url: Option<String>,
    pub thumbnail_width: Option<i32>,
    pub thumbnail_height: Option<i32>,
    pub date_created: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::gallery::Entity",
        from = "Column::Gallery",
        to = "super::gallery::Column::Pk",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Gallery,
}

impl Related<super::gallery::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Gallery.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
