//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::galleries::Entity as Galleries;
pub use super::gallery_posts::Entity as GalleryPosts;
pub use super::seaql_migrations::Entity as SeaqlMigrations;
