//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::gallery::Entity as Gallery;
pub use super::gallery_post::Entity as GalleryPost;
pub use super::seaql_migrations::Entity as SeaqlMigrations;
