//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "gallery_posts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub pk: i32,
    pub gallery: i32,
    pub discord_message_id: i64,
    #[sea_orm(column_type = "Text")]
    pub link: String,
    pub date_created: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::galleries::Entity",
        from = "Column::Gallery",
        to = "super::galleries::Column::Pk",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Galleries,
}

impl Related<super::galleries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Galleries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
