//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "galleries")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub pk: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub channel_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::gallery_posts::Entity")]
    GalleryPosts,
}

impl Related<super::gallery_posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GalleryPosts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
